### ISSUE TITLE
Integrate client-side MVC library(?)

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#128]
> Issue to be tackled after the jam

We have few JS-heavy pages (mostly `edit-entry`), but picking a client-side lib would give us more freedom and more maintainable code.

Ideally:
* Easy to learn
* Model/View bindings for cleaner code
* Does not require compiling/transpiling
* Easy to distinguish with server-side templating (Nunjucks)

For now **[KnockoutJS](http://knockoutjs.com)** seems a good option (note: jQuery would then stay around for Ajax requests, then again we still need it if only for Select2).

**Comment by coxm** [comment]
A few thoughts:

- It would be nice if we could almost completely remove the JS from the templates. Having it in templates makes it hard to edit/lint/minify/etc., and more likely to be duplicated. I think it's preferable to create a core JS library and call functions from it with values from the server, regardless of the framework choice.

- Since we're considering a JS framework (and so requiring all users to run the site with JS), would you consider having a front-end app and separate API? Doing so makes it easier to maintain (the responsibilities are split clearly into two separate parts), and would mean e.g. the front-end app could be delivered by CDN which would help if/when the site gets really busy. In practice I find this makes bottlenecks in need of optimisation easier to find. It also relieves the server of its template-rendering work (again helpful for a busy site).

- As useful as (if not more than) having something easy to learn is having something _people already know_. Given trends in web dev I think React should at least be considered. If you want something simpler, then [VueJS](https://vuejs.org/v2/guide/) might be worth looking at. For AJAX I would consider using shimmed `fetch` or something framework-specific (don't get me wrong; I still :heart: jQuery).

- Why would you prefer *not* to compile code? Doing so is a small overhead but a preprocessing or compilation step would make the site more robust and easier to maintain. For example we could add linting and minification, and ensure code is fit for ES5 (or even ES3) browsers (currently nothing to stops a developer from using ES6 features, supported in their browser, in a template; this would crash the site when visited on an older browser). It also means the code becomes easier to write, as we could use features like async/await everywhere.

- Please consider using some form of type checking! I promise it will make things easier as the site grows and things change. Using an MVC framework means a considerable rewrite of the client-side JS, meaning this would be a perfect time to add one.

**Comment by mkalam-alami** [comment]
* **Removing JS from the templates** : 100% agreed, I knowingly went for the hacky route until we get a better idea of what our front-end looks like, but it was definitely temporary. Linting & minifying will be important indeed. Same for the CSS, which has grown big and which I'd like to explode into several files for easier development.
* **Separate front-end/API,  React**: I'm not exactly sure what you have in mind, but the big thing I'd like to clarify is *I still consider Alakajam as just a "web 2.0" website, not an app*. The use cases are still 80% of browsing everyone else's data like in a news site, Github or Wikipedia, so I'm still happy with the general site architecture. Rebuilding the site with what I feel is a more complex approach, while trying to figure out SEO, etc... with the main goal to just improve performance sounds overkill to me (I'd put templating quite behind the database in the list of potential future bottlenecks).
Also, a more practical concern is, if we had gone with an LDJam-like architecture, we would definitely not have gotten this far in just 5 months of free-time work. Part of why I gave up contributing to LDJam is how bloated the architecture & REST API feels to me.
Having said that, I'm not against using React/Vue for JS-heavy pages, and you're right that people might be more comfortable with React than Knockout.
* **Code compiling**: I'm not really against them, I'm mostly for keeping the dev workflow as tight as possible I'd like not to run build commands between each code change. I admit prefering no-transpiling is mostly just laziness from my part, and we'll have to set up a build system at some point anyway (#21).
* **Type checking**: Again no real issues against that, other than a tight dev workflow, and of course keeping the barrier to entry as low as possible. If we switch to TypeScript, we'll probably do it both for server & client-side for consistency, which would raise another interesting question: "do with stick with Bookshelf"? :P

**Comment by ttencate** [comment]
I wholly agree with @mkalam-alami on all of that. Especially the "let's not build an SPA" bit.

* SPAs take much more experience and discipline to get right, compared to plain old HTML templates: error handling, testing, deploying, SEO, even something as basic as URL structure, all become a lot harder. And an SPA isn't even necessarily faster, because the calls that would normally happen between the server and the database now have to happen between the _client_ and the database.

* TypeScript offers the most benefit if you can use `--noImplicitAny` to guarantee that the code is fully typed. But (afaik) this means you have to have a TSD for each little library you use, which you need to write if none is available. I've also had trouble in the past with incorrect TSDs, which guarantees that your code either compiles, or works correctly, but not both at the same time. I'm not against TypeScript per se, but it does limit the library choice somewhat to the better-known, better-maintained projects. That's not necessarily a bad thing though! But I think modern ES6 (transpiled to ES<6) offers most of the benefits already, like classes and arrow functions, without the drawbacks of using TypeScript.

**Comment by coxm** [comment]
I don't remember mentioning speed, but was concerned about server load (think LD during the last hour or so) in future, especially since everything is in the same place. That said I misunderstood the intention and am **very happy not to build an SPA** :+1: 

In that case before even looking at MVC libraries maybe we should refactor, moving JS out of templates and seeing how much can be consolidated into a core library. Looking at `edit-entry.html` I expect some parts could be replaced with lodash and others would be better suited in the core lib. Perhaps after this the code would be maintainable enough :crossed_fingers: 

As for code compilation, there are lots of solutions which involve file watching and recompilation on changes (for example) instead. I quite like using commands but it's very easy to automate too :man_shrugging: 

Regarding type checking: as there isn't a huge amount of client-side code, I'm happy to continue with raw ES3 if that's preferred. Please bear in mind the following though.
- Raw ES3 or even ES5 has its own difficulties which are somewhat eased when transpiling.
- Actually, [importing untyped modules is possible](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#untyped-imports), though in practice I've never had to use it.
- TS is indeed more helpful with `--noImplicitAny`, but still has huge benefits without: implicit `any` affects only a small proportion of the code.
- As I see it the ES6 features are a tiny section of TypeScript's benefits. Don't forget improved correctness, easier maintenance and far better documentation, to list a few.
- Granted, definitions aren't always totally correct. But issues can often be solved with small, extra definitions; the library can be forked if that fails; there are tools which automatically generate typings; and the compiler can deduce definitions from the JS source. This is no more of an issue than bugs in libraries, and in practice I haven't struggled with definitions for several years.
- Though having type checking for both client- and server-side JS would IMO be better, neither requires the other. It seems appropriate to consider for the client-side code here as we're discussing potentially large changes.
- It's also possible to type-check raw JS, lowering the barrier to entry.
- TypeScript isn't the only option. [Flow](https://flow.org/) is very popular and there may be others which are more suited here.

**Comment by ttencate** [comment]
So we're all agreeing, yay! :) All this is getting a bit offtopic though. This issue was just about client-side libraries, which is a largely orthogonal question. I like React and have some experience with it, but I think Knockout might be a better fit here. It seems to be more suited for adding small dynamic bits to a mostly static page. And it's a much smaller download.

**Comment by ttencate** [comment]
I wonder if we should even keep jQuery. Between Knockout.js, a `querySelector` polyfill added in #21, and perhaps a small AJAX library, we might not need it anymore.

**Comment by ttencate** [comment]
Doing some research.

* **Angular**, **React**, **Ember**, **Backbone**: Too heavyweight and/or geared towards SPAs (include routers and such).
* **Knockout**: Does just data binding, easily integrates into existing static pages. Supposedly not very actively maintained, but quite stable because of that.
* **Vue**: Small. Similar to Knockout, but seems to be a bit more modern and more popular. [Comparison](https://vuejs.org/v2/guide/comparison.html) with other frameworks seems fair and useful. The main drawback of Vue compared to Knockout seems to be that Vue only supports IE9+, but I doubt the site would work in IE8 and before anyway, and we're surely not going to be testing that.

Overall, I'm leaning towards Vue.js. I'm going to take it for a spin and see how it works out in practice.

**Comment by mkalam-alami** [comment]
I'll look into vue.js as well then!

> I wonder if we should even keep jQuery [...] we might not need it anymore.

Actually it is depended on by various UI components like Select2, FlipClock, and the Bootstrap date picker. Nothing impossible, but unfortunately jQuery is still kinda the norm for this sort of gadgets. Maybe [Zepto](http://zeptojs.com/) can work as a lighter dropin replacement?

**Comment by ttencate** [comment]
Tedious: initial form values are currently set using Nunjucks `value="{{ ... }}"` syntax, but Vue.js's `v-model` directive ignores that and treats the JavaScript model unconditionally as the source of truth. Also: `{{ ... }}` is also used in inline scripts. We'll need another way to initialize values.

We could use a tiny inline script for that, which just calls some initialization function with the proper interpolated values. But it seems ([source](https://mozilla.github.io/nunjucks/templating.html#autoescaping)) that Nunjucks's autoescaping is not context-aware, so it'll wrongly escape `&<>` while leaving the more dangerous `\` alone. A solution would be to write a custom filter (`var post = {{ post.title | safe | jsString }};`) but forgetting it in even one place would open up an XSS attack vector.

The same problem is there with Knockout.js as well. Meh.

**Comment by coxm** [comment]
It would be nice if we could just polyfill `fetch` for AJAX. That said, I don't think there's an urgent need to remove jQuery. For one thing if using Vue we'll likely wrap select2 and other widgets in Vue components, and so will need it around. If we're desperate to shift a few kb off our books, we can use a CDN. Every browser in the world will have several versions of jQuery cached and ready to go.

**Comment by ttencate** [comment]
Not yet clear we're going to need this.

**Comment by coxm** [comment]
It was in response to this, i.e. only necessary if dropping jQuery. 
> I wonder if we should even keep jQuery. Between Knockout.js, a querySelector polyfill added in #21, and perhaps a small AJAX library, we might not need it anymore.

**Comment by mkalam-alami** [comment]
Current system looks good enough for now (single minified output file, no worries about browser compat, etc.). We'll reconsider an MVC lib if the need appears.
