### ISSUE TITLE
Nav bar layout issues on certain pages

### ISSUE THREAD

**Issue by euske** [alakajam-team/alakajam#130]
In this page, https://alakajam.com/1st-alakajam

I found the two navigation bars a little confusing because their roles are not immediately clear to the first time users.

My suggestions: make a little space between the two bars, use a different background color for the 2nd bar (not the same as the text background), make the first bar more pronounced, or indent the 2nd bar to clearly indicate the user it's a subtopic (or make it narrower, use a smaller fonts, etc).

**Comment by mkalam-alami** [comment]
Thanks for the feedback. Here's my attempt at clarifying things:

* Changed the 2nd dropdown to better show it belongs to the event subtopic
* Added a drop shadow to avoid white-on-white confusion

What do you think?

![capture2](https://user-images.githubusercontent.com/694508/30486056-b56265f2-9a2f-11e7-95e4-1fc46cd7ac48.PNG)

**Comment by mkalam-alami** [comment]
...after talking about it with Toasty, maybe you have an issue with the header in general, not just with mobile right? For some reason I only thought of mobile view since I refactored it recently.

**Comment by mkalam-alami** [comment]
Consolidated list of things to try:

* Add margins to the event bar
* Wider main header
* Use drop shadows in headers even when not on mobile
* Front page: move sidebar to the right (as suggested by @rnlf),
* Front page: only have the Alakajam! box contain the sidebar, not the post
* Front page: already display the event header, but with white on red rather than red on white

**Comment by mkalam-alami** [comment]
Most of these details have been fixed since then.

Overall header improvements are planned through #343, closing this.
