### ISSUE TITLE
Comment section: show login name with the @ near the display name

### ISSUE THREAD

**Issue by bombjack73** [alakajam-team/alakajam#173]
Hi,

The @ syntax doesn't work on display name which is quite confusing.
I would be great if it worked on both the registered and display names.

Regards,

Marc

**Comment by mkalam-alami** [comment]
It's actually a tricky topic, because that means we could have clashing names. For instance if I change my display name to Bombjack we'll suddenly both receive the same notifications!

An alternative would be to display the real user name somewhere in the comments so we can see at a glance what is the right mention to make.

Ideally we would have auto-completion, but that's more an idea for the long-term...

**Comment by bombjack73** [comment]
Displaying the login name with the @ near the display name would highly help to clearly indentify that we have to use it to mention so in the comments

**Comment by Aurel300** [comment]
I put the `@` in a couple of places, including post titles and game credits, for consistency.
