### ISSUE TITLE
Markdown editor: HTML Entity encoding in Code formatting

### ISSUE THREAD

**Issue by rnlf** [alakajam-team/alakajam#182]
Not exactly sure how to show you a problem with markdown in markdown, but if you put for example an ampersand in the Code/preformatting backticks, they will show in the final output as [ampersand amp semicolon].

I assume there's some HTML entity encoding going on which is unaware of markdown code blocks?

**Comment by ttencate** [comment]
Seems it's already encoded as `&amp;` (ampersand amp semicolon) in the database, regardless of whether it occurs between backticks or not. So when the markdown-to-html converter runs, it will extra-escape the ampersand in the backticks, as per [the "standard"](https://daringfireball.net/projects/markdown/syntax#autoescape).

How does it end up like that in the database? This is `forms.sanitizeMarkdown` at work, which runs `sanitizeHtml` (escaping the entities), intended to strip (dangerous) HTML from the input.

To fix this, we could store the unsafe Markdown as-is in the database, turn it into unsafe HTML, and then do the sanitization as the very final step in rendering. This would also make the hack for un-escaping `>` (used in quote blocks) redundant.

And if we invoke the sanitization directly from the `markdownToHtml` function, there is no risk of it getting forgotten anywhere.

Objections?

**Comment by ttencate** [comment]
Interestingly, upon output there's _also_ a sanitization pass running, powered by [`xss`](https://www.npmjs.com/package/xss) rather than [`sanitize-html`](https://www.npmjs.com/package/sanitize-html). The two shouldn't bite each other, but it seems like overkill to put them back to back like that. I'm going to fly with `sanitize-html` just because it's by far the more active of the two.
