### ISSUE TITLE
Special case makes the total submitted themes count disappear

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#227]
I think it happened by removing/replacing a theme I already submitted.

It got fixed later by other people submitting themes as well.

**Comment by Aurel300** [comment]
Considering how `_refreshEventThemeStats` is implemented, I don't think it is related to removing / replacing themes. Adding / removing themes doesn't directly change the field. I only noticed the glitched / invisible counters right at the beginning, immediately after the theme voting phase started. Presumably because the theme counters were not set yet (not zero, but `NULL` maybe) and therefore nothing was displayed? I'd guess adding something like `|| 0` to the counter display template should not hurt.

**Comment by mkalam-alami** [comment]
Bug recap:

- [ ] Special case makes the total submitted themes count disappear (possibly fixed by Aurel)
- [ ] It also disappeared when switching to shortlist mode
- [ ] Non-out themes appear as in the top 0% when switching to shortlist mode

**Comment by mkalam-alami** [comment]
There was a big issue where the whole "event_details" row was cleared upon saving an event (the model [wasn't properly loaded](https://github.com/alakajam-team/alakajam/commit/e7966901f3b9ee28e18eeecc42732757b34ae093?w=1#diff-0eac48f2e2b0a97e2119db6159a734a4R590) before writing on it). Not sure how I missed that, at least it's now fixed.

"Top 0%" bug to be followed on #232
