### ISSUE TITLE
Finish migrating the scripts from HTML templates to JS files

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#243]

**Comment by ttencate** [comment]
FWIW I still mean to see this through, just been short on time lately...

**Comment by mkalam-alami** [comment]
Don't worry, I actually wanted to complete this myself, but it's just boring technical debt so it fell down in terms of priorities...

A cookie :cookie: to whoever does this first ;)

**Comment by ttencate** [comment]
Back to working on this.

I'm going to take a slightly different approach, with the aim of eventually being able to load most/all JS in the footer rather than the header. This means inline scripts need to be banned, if they depend on delay-loaded scripts (most do). So instead of this:

```
<div id="some-element"></div>
<script>
  alakajam.something.initSomething('#some-element', someParam);
</script>
```

I'm moving towards this:

```
<div class="js-something" data-param="someParam"></div>
```

It's a more customary approach, and should scale well enough as long as we don't go overboard with the JS. (If we do end up going overboard, a framework like Vue or Angular is more appropriate anyway.) Note the `js-` prefix on the class name, to distinguish it from classes used in CSS. I think these should be kept separate if possible.

This might also make any possible future transition to Vue.js easier; we'd just need to replace the classes with Vue'ish attributes, but can continue using the `data-` attributes as is.

**Comment by ttencate** [comment]
Documented the above on https://github.com/alakajam-team/alakajam/wiki. Pushed a couple commits moving towards this.

**Comment by mkalam-alami** [comment]
I also prefer the triggering classes over the inlined bootstrap code.

@Aurel300 Can you confirm all your work is already pushed? Just to make sure you guys don't end up with conflicts

**Comment by Aurel300** [comment]
@mkalam-alami Yeah, sorry, I assigned myself, whoops ^^

I saw there was a bunch of these inline scripts but didn't touch them since they contained parameters. @ttencate's solution (custom CSS classes to trigger JS stuff) is a much nicer solution.

**Comment by ttencate** [comment]
Whew, I think I'm done here! I sincerely hope I fixed more than I broke ;)

**Comment by mkalam-alami** [comment]
![giphy](https://user-images.githubusercontent.com/694508/37967419-964a99a8-31cb-11e8-8a67-99941eba44ed.gif)
