### ISSUE TITLE
CSRF vs File uploads: improve code design

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#294]
So I'm facing a little design issue here, it seems simple but I'm not sure what's the best way to solve it.

### How things were before

Forms were parsed by manual calls to a `await req.parseForm(uploadInfo)` function, which itself uses [multer](https://github.com/expressjs/multer). The `uploadInfo` param contains the **names of the fields to be parsed as files** (eg. "avatar" if there's just one).

### What we need

The [CSURF](https://github.com/expressjs/csurf) lib provides an Express middleware to check the form data for the `_csrf` field.

This means... that when we reach the CSURF middleware, the form data **has to be already parsed**. Which is not possible in that state since we parse the form directly from the controllers. But if we instead parse the form before we reach the controller, how can we know the `uploadInfo` data we have to pass to `req.parseForm()`?

### What I did for now

1. Add a GET param to all the forms with uploads, eg. `<form action="?upload=avatar" ...`
1. Call `req.parseForm()` from a middleware before the controllers, using the GET query params to build `uploadInfo`
1. Put the CSRF protection middleware just after

It works, but the `<form action="...">` trick feels hacky to make uploads work. Someone not understanding the context will probably find this bizarre. I wonder if there is a simple, cleaner approach I just didn't think of.

> Note: if we keep this we'll have to clean up the now obsolete req.parseForm() calls all over the controllers code, as the data is already available in `res.locals.form`

**Comment by ttencate** [comment]
Is it possible to tell from the request which fields were actually file uploads? For example, by checking for `Content-Disposition` that contains a `filename`? See the end of https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2 for some examples of `multipart/form-data` encoded requests. Maybe Multer's [`any()`](https://github.com/expressjs/multer#any) function already does just that, but the [tests](https://github.com/expressjs/multer/blob/eef091188d3f2c40d0da145d75114434b2b3f840/test/expected-files.js#L98) only show it receiving files, not regular form fields.

Though I wonder if we have a security risk if we let the client control which form fields are parsed as file uploads. That would be the case with your hack, but with the above approach as well. In fact, the multer README warns against this:

> WARNING: Make sure that you always handle the files that a user uploads. Never add multer as a global middleware since a malicious user could upload files to a route that you didn't anticipate. Only use this function on routes where you are handling the uploaded files.

I somehow feel that Multer's design is flawed, because it mixes parsing of the request body with storing of files to the filesystem. If files could just be kept in memory and saved inside the controller (after the necessary checks), this problem wouldn't exist. I think this is what the [`MemoryStorage`](https://github.com/expressjs/multer/blob/master/storage/memory.js) engine is for.

Of course, not streaming uploads straight to disk would cost some performance and memory, but if we put a cap on the total request body size, it shouldn't get too bad. It's a choice between being DOSable by running out of disk space or by running out of RAM.

**Comment by mkalam-alami** [comment]
Alright, I moved multer and csurf integration to the routes themselves, [it looks reasonably good to me](https://github.com/alakajam-team/alakajam/blob/master/controllers/index.js), and much more standard than the `req.parseForm` spaghetti.

All that's left now is to effectively remove [the now deprecated](https://github.com/alakajam-team/alakajam/blob/master/core/middleware.js#L198) `req.parseForm` function from the controllers.

Thanks @ttencate and @coxm for the chat.
