### ISSUE TITLE
Is Babel really transpiling correctly?

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#298]
We're having JS issues with (very) old browsers such as Firefox 29.

@ttencate When checking the `static/site.js` build, it seems like we still have ES2015 syntax in it, like const/let. Isn't `preset-env` supposed to fully downgrade the code to ES5?

I noticed in `webpack.common.js` a possible configuration issue, as from what I've read

```
      {
        test: /\.js$/,
        include: rootPathTo('static/js'),
        loader: 'babel-loader',
        options: babelOptions
      },
```
should look more like that according to the docs:

```
      {
        test: /\.js$/,
        include: rootPathTo('static/js'),
        use: {
          loader: 'babel-loader',
          options: babelOptions
        }
      },
```

Now despite the change (or any change for the matter, even clearing `rules: []`) the producted `static/site.js` remains exactly the same :crying_cat_face:

**Comment by ttencate** [comment]
The [full configuration docs](https://webpack.js.org/configuration/module/#rule-loader) explain that `loader` and `options` are just shortcuts. Or maybe also a backwards compatibility thing. I'll write it out in full to prevent any future confusion.

The root cause is simple; this path is wrong (should be `assets/js`), so none of our code was matched by the filter:

```
        include: rootPathTo('static/js'),
```

Note that `preset-env` does not necessarily rewrite code to ES5. Rather, it rewrites only those features that are not available in all target browsers. For example, `const` is sufficiently supported in Firefox 29 so it's not rewritten, but `let` is.

The feature support matrix is supplied by `browserslist` and configured in `package.json`:

```
  "browserslist": [
    ">1%",
    "last 2 versions",
    "IE >= 9"
  ]
```

It's nice to have this in this central place, so that CSS preprocessors use the same set of browsers without keeping the list in two places. However, what I overlooked is that `package.json` is not processed by Babel before 7.0 (as you apparently noticed in commit 80a7abc).

So I'm going to upgrade Babel while I'm at it, and deduplicate the (now out of sync) settings. This might even shrink our bundle a bit, because we can enable `useBuiltIns: 'usage'` to include only those Babel polyfills that we actually use.
