### ISSUE TITLE
Consider Wilson score for theme voting

### ISSUE THREAD

**Issue by ttencate** [alakajam-team/alakajam#304]
The recent discussion (#303) around theme voting has made me think. Theme voting, where we try to determine which theme is "best" (will receive the largest percentage of upvotes) is actually a [multi-armed bandit problem](https://en.wikipedia.org/wiki/Multi-armed_bandit). This is the problem of a gambler faced with multiple slot machines, each with different payout probability, wanting to maximise their profits. They need to balance exploration (trying new or less promising machines to determine their expected payout) against exploitation (using the best slot machine to make the most money). Exploitation in our case would be to gather as many votes as possible for the higher-ranking themes, so the upvote percentage for these is as accurate as possible.

An optimal strategy exists, although I haven't looked into how difficult it is to implement, nor how computationally efficient it is.

Pros:

* Theoretically optimal way to determine themes.
* Submitted themes don't have to be ruled "out" completely. They will just gradually receive fewer and fewer votes if they are deemed unworthy.
* _Maybe_ more fair to themes that arrive later? More research needed.

Cons:

* Less transparent what's going on? But to be honest, I don't understand the current system either.
* Work.

Discuss!

**Comment by mkalam-alami** [comment]
Ok so the idea here is to replace an elimination system with a more clever algorithm that picks the next themes to rate depending on:

* Their percentage of upvotes
* How many votes they received already
* Possibly the date of the last vote
* (maybe more)

The most straightfoward way I could see it implemented is in the form of a... karma/coolness value (again?), using a formula of sorts to turn the above inputs into a single number. This draws comparison to Reddit's post sorting system, that takes the "freshness" of posts in account for their visibility.

The big **PRO** I have for this approach is that it scales better that the current system. The algo right now eliminates themes once in a while according to arbitrary constants (every N1 votes, assuming there's enough themes with N2 votes). This means having an unexpected number of submissions means themes can be eliminated too fast/too slowly. Another pro is that it doesn't prevent us from still eliminating themes if they fill some criteria (I actually like making people come back to see if their themes are still in).

On the **CONS** side, this would make us hide some information, like the number of votes one's themes received so far: if a theme seems to receive few votes, it's probably because it's not doing as well as the others (granted it depends on the algo). I also agree with your cons... This does not seem to help with #303 too much, the process would remain quite obscure but... as long as it's fun \*shrugs\*

**Comment by mkalam-alami** [comment]
Unrelated: On top on tweaking the elimination algo, we should do something about people able to submit themes until the last minute. Unfortunately today Sorceress submitted one in the last hours, that if it weren't for the 10 missing votes would have gotten into the shortlist.

**Comment by ttencate** [comment]
https://redditblog.com/2009/10/15/reddits-new-comment-sorting-system/ is pretty much exactly the algorithm we are looking for. Would need a minimum vote count for themes to qualify for the final round, though. Maybe close theme submission a few days in advance?

**Comment by ttencate** [comment]
Well, _you_ found it :grin:

**Comment by mkalam-alami** [comment]
I'm looking into implementing this Wilson equation (slightly late for AKJ4, but I can probably shoehorn the update a couple days in).

That requires us to choose for each problem:
* Whether to use high or low bound
* And especially which confidence level to use (we'll use insanely high confidence values so let's talk directly in "zα/2" values as per http://www.evanmiller.org/how-not-to-sort-by-average-rating.html)

* **Choosing themes to eliminate**: We'll watch for lowest high bound values. A bad theme typically has 25-30% of positive ratings. I'd like to make sure themes don't end in the mix for elimination before around 10 votes. Using **z=3** gives us *0/10 positives* to be roughly equivalent to *7/30 positives*.
* **Choosing when to eliminate a theme**: Instead of picking 1 theme every N votes, we could simply set a high bound floor. A **0.58 value** would kill: 0/7 positives, 1/9, 2/11 ... 5/16 (ie. typical bad theme is out after ~20 votes), and all themes above 43% would never get killed (about 1/5 of all themes manage that). We could probably use to still keep a **minimum number of votes set to 15**.
* **Choosing the shortlist**: We'll watch for highest low bound values. A great theme usually has 55-60% positive votes and up to 100 votes. I'd like winning themes to at least have 20 votes. Using **z=5** gives us *18/20 positives* to be roughly equivalent to *60/100 positives*.
* **Choosing the winner**: All shortlist themes have the same number of votes. If feel the current system is still valid, as long as we make sure all themes start at 0 at the beginning of the shortlist week (not exactly the case currently).

**Comment by mkalam-alami** [comment]
Logically you're absolutely right, I just wanted to keep somehow that gamification aspect of seeing our themes getting potentially eliminated at any time.

The Wilson equation is still interesting when keeping the eliminations, because better themes will stay up for longer/more votes than bad ones. If you submit your theme early, the longer the theme stays, the more hopes you have that you'll make it to the shortlist!

**Comment by mkalam-alami** [comment]
The implementation takes surprisingly little changes btw.

Todo-list:

- [x] Model changes
- [x] Store wilson scores on themes
- [ ] Store positive + total notes rather than sum of +1/-1 scores
- [ ] Update the theme elimination process
- [x] Update the shortlist selection process
- [ ] Bonus: Make sure than score used for shortlist round starts at 0
- [ ] TESTING APLENTY

**Comment by mkalam-alami** [comment]
And it's online! The theme administration page is looking increasingly nerdy. I'm looking forward to see how the algo does throughout the week.

![clipboard08](https://user-images.githubusercontent.com/694508/46250102-0372d180-c434-11e8-981d-f35dbb95d983.png)
