### ISSUE TITLE
Display below a post the list of users who gemmed it

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#324]

**Comment by Thrainsa** [comment]
![likes](https://user-images.githubusercontent.com/7467127/54482216-98318600-4840-11e9-8317-abd18fdb6881.png)

I add an icon next to the gems so you can check who gemmed a post.
For now I only add this on a post page but that's should not be a problem to add it elsewhere except that it will add some queries (a select on likes with a join on user table for each post)

What do you think of it?

**Comment by mkalam-alami** [comment]
Ok for only listing them in the full post! I'm not a big fan of the tooltip, maybe make a list in the post footer? "Gemmed by " + a list of avatars icons could be nice

**Comment by Aurel300** [comment]
I also wouldn't use the `?` icon for this, since I understand that as help for "what is gemming?". If it is a tooltip, have it on the number or the gem for instance. If not a tooltip, the footer is indeed a nice place for it.

Partly related to this issue: I think the comment + gem icons and numbers should not be in the header when you are viewing the full post. That would also make more sense if the gemmers are in the footer of the post.

**Comment by mkalam-alami** [comment]
Moved to [Feature requests](https://github.com/alakajam-team/alakajam/wiki/Feature-requests) page for now.
