### ISSUE TITLE
Consider a "hot" ranking of blog posts

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#326]
Now that we have a like system, the next logical step would be to use it to sort posts on the front page.

Scoring system can be inspired by https://medium.com/hacking-and-gonzo/how-reddit-ranking-algorithms-work-ef111e33d0d9

**Comment by ttencate** [comment]
I would not like this to be the default. Social media try to "optimise for user engagement" by showing popular stuff (read: cat videos) only, but this is not Alakajam!'s goal. I think our goal should be to help people discover good/interesting posts that they might otherwise have missed, but _not_ at the expense of less popular posts.

Reddit's _comment_ ranking system doesn't take time into account at all, which makes it unsuitable for ranking posts because we'd want some degree of freshness there.

Reddit's _post_ ranking system pretty much requires downvotes to work, otherwise it gets into the "popular posts get more upvotes" feedback loop. And even with downvotes, it's still far from perfect because more controversial posts attract more downvotes. We could implement downvotes as "views that did not lead to upvotes", but then we'd have to go full out Big Brother to record "views" (tracking scrolling on the front page, etc.). Also, the way time is added to the ranking equation is downright silly.

Hacker News [might do this better](https://medium.com/hacking-and-gonzo/how-hacker-news-ranking-algorithm-works-1d9b0cf2c08d), with an easier to understand formula. If we must do something "smart", this would be my preference.

But our goal could be achieved with a dumber and more transparent approach: a filter on the chronological list, e.g. `all` (default), `≥5 gems`, `≥10 gems`, `≥20 gems`. It does suffer slightly from the nasty "popular posts get more gems" feedback loop, but because we still order by time and not by gems, it shouldn't be too bad.

Or an alternative idea: add a box with 3-5 "popular posts" (better naming TBD). These are the latest posts that have at least 5 gems. We only show the title and maybe a _very_ short snippet, no images, and we don't let people gem the post straight from this box. Where this box would go on the already cluttered front page, I don't know.

**Comment by mkalam-alami** [comment]
I agree with no downvotes. They would not be appropriate to our community, and in general I feel they contribute too much to the "sheep mentality" that Reddit's system favors (especially in comments). (note: downvotes are completely disabled on [/r/alakajam](https://www.reddit.com/r/alakajam))

Now regarding sorting/filtering posts, I'd say our end goal is to reward visibility to interesting posts having effort put into them (like postmortems, jamming tips, interestin jam progress reports, etc.) over the less constructive ones. In particular, invites to rate a game are becoming a thing lately, just like on LDJam where people complain about how it bypasses the coolness system. At least on AKJ I feel spamming a game is less effective...

A hotness formula of sorts would be the most straightforward way to help with that. Though maybe we can be more creative, what would you think of:
* Limiting the number of posts a user can make during an event
* Displaying a "warning" when writing a blog post during the rating phase, to discourage simple invites to rate your game
* Adding a report system with options to make "lazy 'rate me' posts" (which could lead to visibility penalties)

If we stick to some form of "hot" ranking, Hacker News' algo is cool in its simplicity indeed. Maybe we could start with that and incorporate the `log(votes)` idea from Reddit that prevents hugely popular posts from clinging to the front page.

I'm less a fan of the post selection/filters, to me they would have similar effects as the "top" sorting in Reddit, which lets people show what's best *only* and kills post discoverability.

**Comment by mkalam-alami** [comment]
Not a priority, the consensus is that it will be helpful once we become popular. Meanwhile our only issue is preventing spam posts requesting votes during jams.

Issue added for reference to the "Site features wishlist" doc.
