### ISSUE TITLE
discrepancy in theme vote stats

### ISSUE THREAD

**Issue by bremco** [alakajam-team/alakajam#573]
![Screenshot_2020-09-06_08-06-52](https://user-images.githubusercontent.com/30440932/92320111-46298500-f01f-11ea-85e3-1953f06bb389.png)

As you can see in the image, there are 162 _active_ ideas. Of course, 10 of these are my own. Yet, my vote total is _151_ rather than 152 (152 + 10 = 162). So it's off by one for some reason.

For completions sake, yes, I do get the _No more themes to vote on!_ message.

I know it can be off by two as well, before the 3rd theme was eliminated and another user joined, the numbers where 153 active ideas (155 total), and I had 141 votes. So it's not, for better or worse, some kind of off-by-one error.

Is this a bug or is there some condition I've overlooked? Or is it that CHAOS person? I liked them when they gave me more themes to play with, but messing with stats is not OK in my book ;-)

_Edit_: P.S. My username on the live site is remco -- should you need it.

**Comment by Aurel300** [comment]
I also noticed a similar issue that might be an off-by-one bug, or a miscount somewhere, although it may also just be a coincidence …

As I was voting on themes, I was getting close to the end of available themes. I voted on theme A, then theme B displayed. I changed my mind on theme A, so I pressed the button in the "recently voted list". The page refreshed as it registered my vote, and then said "no more themes to vote on". What happened to theme B?

**Comment by mkalam-alami** [comment]
Both issues are indeed the same thing, it's due to a hidden rule that says "do not show themes to vote on if less than a certain number remain".

This was set up to avoid cases where X has rated all the available themes, then he chats with Y who says they just submitted theirs... then X sees new themes pop up and obviously they are Y's, which can influence his vote. This also combines weirdly with the fact that themes are loaded in the brower in bulk (groups of 10 themes), leading to situation like Aurel's.

Maybe we can simply get rid of this rule? It's just us trying too hard to protect anonymity and prevent mild cheating.

**Comment by bremco** [comment]
> Maybe we can simply get rid of this rule? It's just us trying too hard to protect anonymity and prevent mild cheating.

That's up to you (I mean it would be in any case, but even more now). I'm just relieved that its not a bug.

That said: A lot of (the) jam(s) already work on a honours system. Hopefully in the future the amount of people joining will prevent cheating like this anyway (as it becomes noise). The more complicaties the code, the higher the chance to introduce bugs (or confusing behaviour).

But like I said, for me personally it's enough to know that it's on purpose.
